services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # Fix Vite so it listens on all network interfaces
    command: ["npm", "run", "dev", "--", "--host"]
