services:
  backend:
    build: ./backend
    ports:
      - "5000:6000"
    # environment:
    #   - PORT=${PORT} # pass PORT into the container
    # env_file:
    #   - .env
    # env_file:
    #   - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # Fix Vite so it listens on all network interfaces
    command: ["npm", "run", "dev", "--", "--host"]
